test:
  services:
    - mongo
  image: python:3.6
  variables:
    ENV: "test"
  script:
    - apt-get update -q -y
    - cd analysis
    - pip3 install -r requirements.txt
    - python3 setup.py
    - cd test
    - pytest
