test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - cd analysis
  - pip3 install -r requirements.txt
  - python3 setup.py
  - pytest